name: acoc
dependencies:
- appnope=0.1.0=py35_0
- cudatoolkit=7.0=1
- cycler=0.9.0=py35_0
- decorator=4.0.6=py35_0
- freetype=2.5.5=0
- ipykernel=4.2.2=py35_0
- ipython=4.1.1=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_1
- jupyter_client=4.1.1=py35_0
- jupyter_console=4.1.0=py35_0
- jupyter_core=4.0.6=py35_0
- libpng=1.6.17=0
- llvmlite=0.8.0=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- mkl=11.3.1=0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.1.0=py35_0
- numba=0.23.1=np110py35_0
- numpy=1.10.4=py35_0
- openssl=1.0.2f=0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.0.2=py35_0
- ptyprocess=0.5=py35_0
- pygments=2.1=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- python.app=1.2=py35_4
- pytz=2015.7=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.1.1=py35_0
- readline=6.2=2
- scikit-learn=0.17=np110py35_1
- scipy=0.16.1=np110py35_0
- setuptools=19.6.2=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - alabaster==0.7.7
  - babel==2.2.0
  - blessings==1.6
  - bottle==0.12.9
  - bpython==0.15
  - cprofilev==1.0.7
  - curtsies==0.2.6
  - docutils==0.12
  - greenlet==0.4.9
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - requests==2.9.1
  - snowballstemmer==1.2.1
  - sphinx==1.3.5
  - sphinx-rtd-theme==0.1.9
  - wcwidth==0.1.6

